# Documentation: http://www.privoxy.org/user-manual/actions-file.html

{ +filter{plusone}}
/

{+block{Block Yahoo Analytics}}
s.yimg.com
.analytics.yahoo.com

{+block{Block Google Analytics and ads}}
.google-analytics.
.googleadservices.com
plusone.google.com
.googlesyndication.com

{+block{Block Twitter buttons}}
platform.twitter.com/widgets

{+block{Block other trackers}}
.insites.
.metriweb.be
.adhese.be
.scorecardresearch.
.2mdn.
.doubleclick.
.tacoda.
.revsci.
.chartbeat.
.addthis.
.sharethis.
.z5x.
.pgmediaserve.
.quantserve.
.observerapp.
.postrank.
.channelintelligence.com
.reinvigorate.
.lloogg.
.disqus.com
.krxd.
.ethnio.
.ethn.io
.quantserve.
.scorecardresearch.
.atwola.
cs.pebblemedia.be
messagent.vummail.be
rcapp.persgroep.be
cdn.ad4game.com
content.yieldmanager.edgesuite.net
ad.adorika.com
aka-cdn-ns.adtech.de
bs.serving-sys.com
pagead2.googlesyndication.com
.gaug.es
.technorati.com
.stumbleupon.com
.stumble-upon.com
cdn.onswipe.com
.zdbb.net
.reddit.com/static/button.*
buttons.reddit.com
.betrad.com
/metriweb.*
stats.wordpress.com
metrics.amd.com
tweetmeme.com
dc.tremormedia.com
.tribalfusion.com
.tumri.net
.turn.com
.udmserve.net
ads.undertone.com
.w55c.net
ad.wsod.net
.xgraph.net
.yieldoptimzer.com
.yt1187.net
.yumenetworks.com
.rubiconproject.com
.scanscout.com
.sharethis.com
.specificclick.net
.specificmedia.com
.tacoda.com
.tidaltv.com
.trafficmp.com
.33across.com
.abmr.net
.adadvisor.net
.adap.tv
.adblade.com
.adbrite.com
.adchemy.com
.addthis.com
.adlegend.com
tag.admeld.com
.adnxs.com
.adready.com
.adsonar.com
.adtech.de
.adtechus.com
.advertising.com
.adviva.net
.afy11.net
.aggregateknowledge.com
.agkn.com
.amgdgt.com
.atdmt.com
.atwola.com
.bluekai.com
.brilig.com
.btrll.com
.burstnet.com
.casalemedia.com
.cmads.com.tw
.cmadsasia.com
.cmadseu.com
.cognitivematch.com
.collective-media.net
.criteo.com
.crosspixel.net
.crwdcntrl.net
admonkey.dapper.net
.decdna.net
.decideinteractive.com
.displaymarketplace.com
.domdex.com
.dotomi.com
.doubleclick.net
.dtfssearch.com
.exelator.com
.fastclick.net.
.fetchback.com
.ib-ibi.com
.imiclk.com
.intellitxt.com
.interclick.com
.invitemedia.com
.mathtag.com
.media6degrees.com
.mediaforge.com
.mediaplex.com
.mookie.com
.mmismm.com
.mxptint.net
.netmng.com
.nexac.com
.owneriq.net
.pm14.com
.pro-market.net
.pswec.com
.quantserve.com
.raasnet.com
.realmedia.com
.richrelevance.com
.rfihub.com
.ru4.com



{+block{Block web bugs} +handle-as-image}
.2mdn./.*\.[gif|jpg|png]
feeds.feedburner.com
.feedburner.com/.*[gif|jpg|png]$
s.ytimg.com/.*pixel.*gif$

{+block{Block pocker sites} }
.eurogrand.com

