#!/bin/sh

IAM=$(whoami)

rm -rf ~/.oh-my-zsh
rm -rf ~/.dakrone
git clone git://github.com/robbyrussell/oh-my-zsh.git ~/.oh-my-zsh
git clone git://github.com/dakrone/dakrone-dotfiles.git ~/.dakrone

cp -R ~/.dakrone/.emacs.d ~/
mv ~/.emacs.d/hinmanm ~/.emacs.d/$IAM

cp -f -v ~/.dakrone/.zshrc ~/
cp -f -v ~/.dakrone/.oh-my-zsh/custom/*.zsh ~/.oh-my-zsh/custom/
cp -f -v ~/.dakrone/.oh-my-zsh/themes/dakrone.zsh ~/.oh-my-zsh/themes/

cp -f -v ~/.dakrone/.tmux.conf ~/
