#!/bin/sh
#
# Usage:
# % curl -sk https://raw.github.com/dakrone/dakrone-dotfiles/master/bootstrap | zsh

IAM=$(whoami)

rm -rf ~/.zsh
rm -rf ~/.dakrone
mkdir ~/.zsh
cd ~/.zsh && git clone -q git://github.com/zsh-users/zsh-syntax-highlighting.git
cd ~/.zsh && git clone -q git://github.com/zsh-users/zsh-completions.git
git clone -q git://github.com/dakrone/dakrone-dotfiles.git ~/.dakrone

# Only bootstrap the emacs stuff if Emacs 24 is installed
HAVE24=$(emacs --version | grep "Emacs 24")
if [ $? -eq 0 ]; then
    cp -R ~/.dakrone/.emacs.d ~/
    mv ~/.emacs.d/hinmanm ~/.emacs.d/$IAM
else
    cp -R ~/.dakrone/.emacs.d/backup23.el ~/.emacs.el
fi
mv -n ~/.dakrone/bin ~/

cp -f ~/.dakrone/.zshrc ~/
cp -R ~/.dakrone/.zsh ~/
cp -f ~/.dakrone/.gitconfig ~/
cp -f ~/.dakrone/.tmux.conf ~/

echo "Bootstrapped."
