#!/bin/sh

echo "Gathering dotfiles..."

cp -f -v ~/.vimrc .
cp -f -v ~/.zshrc .
mkdir -p .oh-my-zsh/custom
mkdir -p .oh-my-zsh/themes
cp -f -v ~/.oh-my-zsh/custom/*.zsh .oh-my-zsh/custom/
cp -f -v ~/.oh-my-zsh/themes/dakrone.zsh-theme .oh-my-zsh/themes/
cp -f -v ~/.screenrc .
mkdir -p .vim
cp -f -rv ~/.vim .
cp -f -v ~/.nsmcrc .
cp -f -v ~/.vimperatorrc .
cp -f -v ~/.vromerc .
mkdir -p .vimperator
cp -f -rv ~/.vimperator .
mkdir -p .config/irb
cp -f -rv ~/.config/irb .config/
cp -f -v ~/.irbrc .
cp -f -v ~/.autotest .
mkdir -p .newsbeuter
cp -f -v ~/.newsbeuter/config .newsbeuter/config
cp -f -v ~/.conkerorrc .
mkdir -p .elinks
cp -f -v ~/.elinks/elinks.conf .elinks
cp -f -v ~/.gitconfig .

mkdir -p .irssi
cp -f -v ~/.irssi/config .irssi/
cp -f -v ~/.irssi/default.theme .irssi/
cp -f -v ~/.irssi/tzu.theme .irssi/
cp -f -v ~/.tmux.conf .
cp -f -v ~/.config/uzbl/config .config/uzbl/

mkdir -p .emacs.d
cp -f -rv ~/.emacs.d .
# Remove elc files
find . -name "*.elc" -exec rm {} \;
find . -name "*._*" -exec rm {} \;
find . -name "*~" -exec rm {} \;


# Remove cruft
rm -rf .emacs.d/auto-save-list/
rm -rf .emacs.d/backups
rm -rf .emacs.d/tramp
rm -rf .emacs.d/places

