### vim:ft=zsh:foldmethod=marker
###
### .zlogout - just clear the screen
###
### Frank Terbeck <ft@bewatermyfriend.org>
### Last-Modified: Tue Nov 25 18:39:53 2008
###
### URI: <http://ft.bewatermyfriend.org/comp/zsh.html>
###

[[ -x $(which clear) ]] && =clear

